import os
import json
from fastapi import FastAPI
from fastapi.responses import HTMLResponse, FileResponse, Response
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
from typing import Optional, List

app = FastAPI(title="Adaptive 2.5D LiDAR Dashboard")

# Paths
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUTS_DIR = os.path.join(os.path.dirname(BASE_DIR), "outputs")
os.makedirs(OUTPUTS_DIR, exist_ok=True)

app.mount("/outputs", StaticFiles(directory=OUTPUTS_DIR), name="outputs")


# ── Static page ───────────────────────────────────────────────────────────────
@app.get("/", response_class=HTMLResponse)
async def read_index():
    template_path = os.path.join(BASE_DIR, "templates", "index.html")
    with open(template_path, "r", encoding="utf-8") as f:
        return f.read()


# ── Camera frame ──────────────────────────────────────────────────────────────
@app.get("/current_frame.jpg")
async def current_frame():
    # Try front_view.png first (generated by visualizer), fall back to legacy jpg
    for name in ("current_frame.jpg", "front_view.png"):
        path = os.path.join(OUTPUTS_DIR, name)
        if os.path.exists(path):
            mt = "image/png" if name.endswith(".png") else "image/jpeg"
            return FileResponse(path, media_type=mt)
    return Response(status_code=204)


# ── Metrics (latest frame) ────────────────────────────────────────────────────
class MetricsData(BaseModel):
    total_points: int = 0
    processing_time_ms: float = 0.0
    fps: float = 0.0
    terrain: int = 0
    static_obstacle: int = 0
    vehicle: int = 0
    pedestrian: int = 0
    memory_reduction: Optional[dict] = None
    zone_stats: Optional[dict] = None
    frame_index: int = 0
    memory_delta_mb: float = 0.0


def _read_metrics_file() -> dict:
    metrics_file = os.path.join(OUTPUTS_DIR, "metrics.json")
    if not os.path.exists(metrics_file):
        return {}
    try:
        with open(metrics_file, "r") as f:
            return json.load(f)
    except Exception:
        return {}


@app.get("/api/metrics")
async def get_metrics():
    data = _read_metrics_file()
    if not data:
        return MetricsData()

    counts = data.get("class_counts", {})
    return MetricsData(
        total_points=data.get("total_points", 0),
        processing_time_ms=data.get("processing_time_ms", 0.0),
        fps=data.get("fps", 0.0),
        terrain=counts.get("terrain", 0),
        static_obstacle=counts.get("static_obstacle", 0),
        vehicle=counts.get("vehicle", 0),
        pedestrian=counts.get("pedestrian", 0),
        memory_reduction=data.get("memory_reduction"),
        zone_stats=data.get("zone_stats"),
        frame_index=data.get("frame_index", 0),
        memory_delta_mb=data.get("memory_delta_mb", 0.0),
    )


# ── Metrics history (for sparklines) ─────────────────────────────────────────
@app.get("/api/metrics/history")
async def get_metrics_history():
    history_file = os.path.join(OUTPUTS_DIR, "metrics_history.json")
    if not os.path.exists(history_file):
        return []
    try:
        with open(history_file, "r") as f:
            return json.load(f)
    except Exception:
        return []


# ── Push metrics via POST (optional, kept for compatibility) ──────────────────
@app.post("/api/metrics")
async def update_metrics(metrics: MetricsData):
    return {"status": "success"}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
